"""Add missing indexes

Revision ID: 294499487a0a
Revises: 
Create Date: 2026-01-20 18:29:57.168523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294499487a0a'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chat_messages_role', 'chat_messages', ['role'], unique=False)
    op.create_index('ix_chat_sessions_user_pinned', 'chat_sessions', ['user_id', 'is_pinned'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_sessions_user_pinned', table_name='chat_sessions')
    op.drop_index('ix_chat_messages_role', table_name='chat_messages')
    # ### end Alembic commands ###