"""Update database schema - fix metadata field and add new columns

Revision ID: 14ae9506dbd7
Revises: 
Create Date: 2025-11-11 12:04:29.079803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ae9506dbd7'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_chat_sessions_user_id'), table_name='chat_sessions_old')
    op.drop_table('chat_sessions_old')
    op.drop_table('chat_messages_old')
    op.alter_column('chat_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('chat_logs', 'data_source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index('ix_chat_logs_timestamp', 'chat_logs', ['timestamp'], unique=False)
    op.add_column('chat_messages', sa.Column('message_metadata', sa.Text(), nullable=True))
    op.alter_column('chat_messages', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('chat_messages', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_chat_messages_chat_id'), table_name='chat_messages')
    op.drop_index(op.f('idx_chat_messages_chat_id_id'), table_name='chat_messages')
    op.create_index('ix_chat_messages_chat_created', 'chat_messages', ['chat_id', 'created_at'], unique=False)
    op.create_index('ix_chat_messages_chat_id', 'chat_messages', ['chat_id'], unique=False)
    op.drop_column('chat_messages', 'timestamp')
    op.drop_column('chat_messages', 'metadata')
    op.add_column('chat_sessions', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('chat_sessions', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_chat_sessions_incognito'), table_name='chat_sessions')
    op.drop_index(op.f('idx_chat_sessions_user_updated'), table_name='chat_sessions')
    op.create_index('ix_chat_sessions_user_archived', 'chat_sessions', ['user_id', 'is_archived'], unique=False)
    op.create_index('ix_chat_sessions_user_updated', 'chat_sessions', ['user_id', 'updated_at'], unique=False)
    op.drop_column('chat_sessions', 'last_message')
    op.drop_column('chat_sessions', 'message_count')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'oauth_provider',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'oauth_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'last_login',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_oauth', 'users', ['oauth_provider', 'oauth_id'], unique=False)
    op.create_unique_constraint('uq_provider_oauth_id', 'users', ['oauth_provider', 'oauth_id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_provider_oauth_id', 'users', type_='unique')
    op.drop_index('ix_users_oauth', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.alter_column('users', 'last_login',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'oauth_id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'oauth_provider',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('chat_sessions', sa.Column('message_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('chat_sessions', sa.Column('last_message', sa.TEXT(), nullable=True))
    op.drop_index('ix_chat_sessions_user_updated', table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_user_archived', table_name='chat_sessions')
    op.create_index(op.f('idx_chat_sessions_user_updated'), 'chat_sessions', ['user_id', 'updated_at'], unique=False)
    op.create_index(op.f('idx_chat_sessions_incognito'), 'chat_sessions', ['is_incognito'], unique=False)
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('chat_sessions', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('chat_sessions', 'is_pinned')
    op.add_column('chat_messages', sa.Column('metadata', sa.TEXT(), nullable=True))
    op.add_column('chat_messages', sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_index('ix_chat_messages_chat_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_chat_created', table_name='chat_messages')
    op.create_index(op.f('idx_chat_messages_chat_id_id'), 'chat_messages', ['chat_id', 'id'], unique=False)
    op.create_index(op.f('idx_chat_messages_chat_id'), 'chat_messages', ['chat_id'], unique=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('chat_messages', 'role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('chat_messages', 'message_metadata')
    op.drop_index('ix_chat_logs_timestamp', table_name='chat_logs')
    op.alter_column('chat_logs', 'data_source',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('chat_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('chat_messages_old',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('session_id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('message_type', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('data_source', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions_old.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions_old',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('session_id', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('idx_chat_sessions_user_id'), 'chat_sessions_old', ['user_id'], unique=False)
    # ### end Alembic commands ###